-- AlterTable
ALTER TABLE "users" ADD COLUMN     "cash_1" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cash_137" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cash_250" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cash_43114" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cash_56" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cash_8086" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cash_900" DOUBLE PRECISION NOT NULL DEFAULT 0;
