import { tVIPLevelUp } from "@/types/tVIPLevelUp";

import IconBased from "@/assets/icons/vip/based.svg";
import IconBronze from "@/assets/icons/vip/bronze.svg";
import IconCaptain from "@/assets/icons/vip/captain.svg";
import IconCertified from "@/assets/icons/vip/certified.svg";
import IconDiamond from "@/assets/icons/vip/diamond.svg";
import IconGatos from "@/assets/icons/vip/gatos.svg";
import IconGold from "@/assets/icons/vip/gold.svg";
import IconIron from "@/assets/icons/vip/iron.svg";
import IconLegend from "@/assets/icons/vip/legend.svg";
import IconLoyal from "@/assets/icons/vip/loyal.svg";
import IconObsidian from "@/assets/icons/vip/obsidian.svg";
import IconPlatinum from "@/assets/icons/vip/platinum.svg";
import IconRoller from "@/assets/icons/vip/roller.svg";
import IconRuby from "@/assets/icons/vip/ruby.svg";
import IconSilver from "@/assets/icons/vip/silver.svg";
import IconVip from "@/assets/icons/vip/vip.svg";

export const vipData: tVIPLevelUp[] = [
  {
    level: 0,
    vipTitle: "Iron",
    wagerAmount: 0,
    icon: <IconIron />,
    conditions: {
      rakeback: 0.5,
      cashback: 2,
      levelUpBonus: 0,
      cashbackPeriod: "weekly",
      bPrivateVIPPromotions: false,
      bCustomizedBonuses: false,
      bDedicatedVIPhost: false,
    },
    background: "#2B3344",
    color: "#ADACA9",
  },
  {
    level: 1,
    vipTitle: "Bronze",
    wagerAmount: 5000,
    icon: <IconBronze />,
    conditions: {
      rakeback: 1,
      cashback: 3,
      levelUpBonus: 0,
      cashbackPeriod: "weekly",
      bPrivateVIPPromotions: false,
      bCustomizedBonuses: false,
      bDedicatedVIPhost: false,
    },
    background: "#2B3344",
    color: "#C98E6D",
  },
  {
    level: 2,
    vipTitle: "Silver",
    wagerAmount: 10000,
    icon: <IconSilver />,
    conditions: {
      rakeback: 1.5,
      cashback: 4,
      levelUpBonus: 10,
      cashbackPeriod: "weekly",
      bPrivateVIPPromotions: false,
      bCustomizedBonuses: false,
      bDedicatedVIPhost: false,
    },
    background: "#2B3344",
    color: "#DDDFE4",
  },
  {
    level: 3,
    vipTitle: "Gold",
    wagerAmount: 25000,
    icon: <IconGold />,
    conditions: {
      rakeback: 2,
      cashback: 5,
      levelUpBonus: 20,
      cashbackPeriod: "weekly",
      bPrivateVIPPromotions: false,
      bCustomizedBonuses: false,
      bDedicatedVIPhost: false,
    },
    background: "#2B3344",
    color: "#FDCB35",
  },
  {
    level: 4,
    vipTitle: "Platinum",
    wagerAmount: 50000,
    icon: <IconPlatinum />,
    conditions: {
      rakeback: 2.5,
      cashback: 6,
      levelUpBonus: 40,
      cashbackPeriod: "weekly",
      bPrivateVIPPromotions: false,
      bCustomizedBonuses: false,
      bDedicatedVIPhost: false,
    },
    background: "#2B3344",
    color: "#59B0F3",
  },
  {
    level: 5,
    vipTitle: "Diamond",
    wagerAmount: 100000,
    icon: <IconDiamond />,
    conditions: {
      rakeback: 3,
      cashback: 7,
      levelUpBonus: 100,
      cashbackPeriod: "bio-weekly",
      bPrivateVIPPromotions: false,
      bCustomizedBonuses: false,
      bDedicatedVIPhost: false,
    },
    background: "#2B3344",
    color: "#AE8BFA",
  },
  {
    level: 6,
    vipTitle: "Obsidian",
    wagerAmount: 250000,
    icon: <IconObsidian />,
    conditions: {
      rakeback: 3.5,
      cashback: 8,
      levelUpBonus: 200,
      cashbackPeriod: "bio-weekly",
      bPrivateVIPPromotions: false,
      bCustomizedBonuses: false,
      bDedicatedVIPhost: false,
    },
    background: "#2B3344",
    color: "#7FEB6B",
  },
  {
    level: 7,
    vipTitle: "Ruby",
    wagerAmount: 500000,
    icon: <IconRuby />,
    conditions: {
      rakeback: 4,
      cashback: 9,
      levelUpBonus: 500,
      cashbackPeriod: "bio-weekly",
      bPrivateVIPPromotions: false,
      bCustomizedBonuses: false,
      bDedicatedVIPhost: false,
    },
    background: "#2B3344",
    color: "#FF5492",
  },
  {
    level: 8,
    vipTitle: "Loyal",
    wagerAmount: 1000000,
    icon: <IconLoyal />,
    conditions: {
      rakeback: 8,
      cashback: 10,
      levelUpBonus: 1000,
      cashbackPeriod: "tri-weekly",
      bPrivateVIPPromotions: true,
      bCustomizedBonuses: true,
      bDedicatedVIPhost: true,
    },
    background: "#5B616D",
    color: "#7FEB6B",
  },
  {
    level: 9,
    vipTitle: "Captain",
    wagerAmount: 5000000,
    icon: <IconCaptain />,
    conditions: {
      rakeback: 10,
      cashback: 14,
      levelUpBonus: 7000,
      cashbackPeriod: "tri-weekly",
      bPrivateVIPPromotions: true,
      bCustomizedBonuses: true,
      bDedicatedVIPhost: true,
    },
    background: "#92CBF7",
    color: "#08416D",
  },
  {
    level: 10,
    vipTitle: "VIP",
    wagerAmount: 10000000,
    icon: <IconVip />,
    conditions: {
      rakeback: 12,
      cashback: 16,
      levelUpBonus: 15000,
      cashbackPeriod: "tri-weekly",
      bPrivateVIPPromotions: true,
      bCustomizedBonuses: true,
      bDedicatedVIPhost: true,
    },
    background: "#FDD868",
    color: "#4A3902",
  },
  {
    level: 11,
    vipTitle: "Legend",
    wagerAmount: 50000000,
    icon: <IconLegend />,
    conditions: {
      rakeback: 14,
      cashback: 18,
      levelUpBonus: 25000,
      cashbackPeriod: "tri-weekly",
      bPrivateVIPPromotions: true,
      bCustomizedBonuses: true,
      bDedicatedVIPhost: true,
    },
    background: "linear-gradient(180deg, #D2D1CD 0%, #838079 100%)",
    color: "#000000",
  },
  {
    level: 12,
    vipTitle: "Roller",
    wagerAmount: 100000000,
    icon: <IconRoller />,
    conditions: {
      rakeback: 16,
      cashback: 20,
      levelUpBonus: 55000,
      cashbackPeriod: "daily",
      bPrivateVIPPromotions: true,
      bCustomizedBonuses: true,
      bDedicatedVIPhost: true,
    },
    background: "linear-gradient(180deg, #FF9EC1 0%, #FF5492 100%)",
    color: "#000000",
  },
  {
    level: 13,
    vipTitle: "Gatos",
    wagerAmount: 250000000,
    icon: <IconGatos />,
    conditions: {
      rakeback: 18,
      cashback: 22,
      levelUpBonus: 120000,
      cashbackPeriod: "daily",
      bPrivateVIPPromotions: true,
      bCustomizedBonuses: true,
      bDedicatedVIPhost: true,
    },
    background: "linear-gradient(180deg, #C9B5FD 0%, #AE8BFA 100%)",
    color: "#000000",
  },
  {
    level: 14,
    vipTitle: "Based",
    wagerAmount: 500000000,
    icon: <IconBased />,
    conditions: {
      rakeback: 20,
      cashback: 25,
      levelUpBonus: 250000,
      cashbackPeriod: "daily",
      bPrivateVIPPromotions: true,
      bCustomizedBonuses: true,
      bDedicatedVIPhost: true,
    },
    background: "linear-gradient(180deg, #7FEB6B 0%, #38CA22 100%)",
    color: "#000000",
  },
  {
    level: 15,
    vipTitle: "Certified",
    wagerAmount: 1000000000,
    icon: <IconCertified />,
    conditions: {
      rakeback: 22,
      cashback: 30,
      levelUpBonus: 1000000,
      cashbackPeriod: "daily",
      bPrivateVIPPromotions: true,
      bCustomizedBonuses: true,
      bDedicatedVIPhost: true,
    },
    background: "linear-gradient(45deg, #57DD40 0%, #92CBF7 50%, #FDCB35 100%)",
    color: "#000000",
  },
];
