-- AlterTable
ALTER TABLE "users" ADD COLUMN     "cash_ltc" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "ltcAddress" TEXT,
ADD COLUMN     "ltcPk" TEXT,
ADD COLUMN     "wagered" DOUBLE PRECISION NOT NULL DEFAULT 0;
