-- AlterTable
ALTER TABLE "users" ADD COLUMN     "cash_2741" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cash_usdc" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cash_usdt" DOUBLE PRECISION NOT NULL DEFAULT 0;
